### ISSUE TITLE
[Bug] getFlightChargeManager().isEnabled() cause error.

### ISSUE THREAD

**Issue by momoservertw** [Zrips/CMI-API#11]
**Description of issue:**
API: 
```
CMI.getInstance().getFlightChargeManager().isEnabled()
````

Will cause error:
```
java.lang.NoSuchMethodError: com.Zrips.CMI.Modules.FlightCharge.FlightChargeManager.isEnabled()Z
```
---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
[21:06:42 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'pp' in plugin PlayerdataPlus v1.1.3
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.15.2.jar:git-Paper-164]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.15.2.jar:git-Paper-164]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:752) ~[patched_1.15.2.jar:git-Paper-164]
        at net.minecraft.server.v1_15_R1.PlayerConnection.handleCommand(PlayerConnection.java:1825) ~[patched_1.15.2.jar:git-Paper-164]
        at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1633) ~[patched_1.15.2.jar:git-Paper-164]
        at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.15.2.jar:git-Paper-164]
        at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.15.2.jar:git-Paper-164]
        at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.15.2.jar:git-Paper-164]
        at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-164]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Paper-164]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Paper-164]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Paper-164]
        at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1038) ~[patched_1.15.2.jar:git-Paper-164]
        at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1031) ~[patched_1.15.2.jar:git-Paper-164]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.15.2.jar:git-Paper-164]
        at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1015) ~[patched_1.15.2.jar:git-Paper-164]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:938) ~[patched_1.15.2.jar:git-Paper-164]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_231]
Caused by: java.lang.NoSuchMethodError: com.Zrips.CMI.Modules.FlightCharge.FlightChargeManager.isEnabled()Z
        at tw.momocraft.playerdataplus.utils.FlyStatus.onFly(FlyStatus.java:50) ~[?:?]
        at tw.momocraft.playerdataplus.Commands.onCommand(Commands.java:15) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.15.2.jar:git-Paper-164]
        ... 17 more
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
config.yml
```
FlightCharge:
  # When set to true, each time player gets flight charge or relogs, his fly mode will be toggled on
  # If set to false, then players will have to manually turn on flight with /cmi flyc
  EnabledByDefault: true
  # When set to true, in event of player changing his game mode from survival/adventure to creative/spectator his flight charge  mode will get disabled
  # Same applies when changing game mode from creative/spectator to survival/adventure
  AutoSwitch: false
  # How much it costs for one recharge point in exp points. Value can be in decimals, like 0.2 but it cant be equal or lower than 0
  # Set to 0 to disable this type of recharge
  ExpRechargeCost: 1.0
  # How much it costs for one recharge point. Value can be in decimals, like 0.2 but it cant be equal or lower than 0
  # Set to 0 to disable this type of recharge
  MoneyRechargeCost: 1.0
  # Defines maximum amount of charge player can have
  # One charge is one traveled block while flying
  # if player doesn't move, then one charge for each second while hovering
  MaxChargeLevel: 1000
  # Defines multiplier when player doesn't move but is hovering. For each second player hovers.
  # Set to 0 to disable
  DeductOnIdling: 1.0
  # If this is set above 0, then player will loose defined amount of charges each second they are flying instead of traveled blocks
  # Set to 0 to disable, which will deduct charges for traveled blocks
  DeductOnlyForTime: 0.0
  # Defines multiplier when player falls down of charge to be taken
  # This only effects when player falls from above 3 blocks of hight
  # In example if player falls from 10 blocks height, then 7 * 2 = 14 charges will be taken
  # This is to prevent avoiding no penalty from jumping from cliffs
  # Set to 0 if you want to disable it
  DeductOnFallMulti: 2
  # Defines if you want to damage player when he falls down from higher than 3 blocks height
  # This will not kill player even if he would drop from 200 block height, but will leave him with 1 hp
  # This will only effect players who jumped down and not those who disabled fly mode in mid air
  DamageOnFall: true
  # DamageOnFall should be enabled for this to work
  # This will define if you want to damage player when he deactivates fly mode in mid air
  DamageOnToggle: false
  # DamageOnFall should be enabled for this to work
  # This will define if you want to kill player if fall damage if higher than his health amount
  KillOnFall: false
```

Modules.yml
```
ALL ENABLED.
```
---

**Cmi Version (using`/cmi version`):** 
 CMI: 8.6.22.1

**Cmi API Version:** 
CMIAPI7.6.2.0.jar

**Server Type (Spigot/Paperspigot/etc):** 
Paper

**Server Version (using `/ver`):** 
 Paper version git-Paper-164 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

**Comment by Zrips** [comment]
Method got removed at some point so it was causing this issue by trying to trigger method which doesn't exist in new CMI versions.
