### ISSUE TITLE
TabComplete isn't working

### ISSUE THREAD

**Issue by Grantie** [Zrips/CMI-API#47]
When I try the /inv command to see someone's inventory, but when I start typing the player's name, I get errors. For each letter I type, it says, "An internal error occurred while attempting to tab-complete this command". This is my console:

`30.12 22:37:31 [Server] ERROR Exception when ItsGrantie attempted to tab complete inv 
30.12 22:37:31 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing tab-completer for 'inv ' in com.Zrips.CMI.Containers.CommandReg$ReflectCommand(inv)
30.12 22:37:31 [Server] INFO at org.bukkit.command.SimpleCommandMap.tabComplete(SimpleCommandMap.java:246) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
30.12 22:37:31 [Server] INFO at org.bukkit.craftbukkit.v1_20_R3.CraftServer.tabCompleteCommand(CraftServer.java:2518) ~[paper-1.20.4.jar:git-Paper-346]
30.12 22:37:31 [Server] INFO at org.bukkit.craftbukkit.v1_20_R3.CraftServer.tabComplete(CraftServer.java:2490) ~[paper-1.20.4.jar:git-Paper-346]
30.12 22:37:31 [Server] INFO at org.bukkit.craftbukkit.v1_20_R3.command.BukkitCommandWrapper.getSuggestions(BukkitCommandWrapper.java:74) ~[paper-1.20.4.jar:git-Paper-346]
30.12 22:37:31 [Server] INFO at com.mojang.brigadier.tree.ArgumentCommandNode.listSuggestions(ArgumentCommandNode.java:71) ~[brigadier-1.2.9.jar:git-Paper-346]
30.12 22:37:31 [Server] INFO at com.mojang.brigadier.CommandDispatcher.getCompletionSuggestions(CommandDispatcher.java:544) ~[paper-1.20.4.jar:?]
30.12 22:37:31 [Server] INFO at com.mojang.brigadier.CommandDispatcher.getCompletionSuggestions(CommandDispatcher.java:524) ~[paper-1.20.4.jar:?]
30.12 22:37:31 [Server] INFO at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleCustomCommandSuggestions$5(ServerGamePacketListenerImpl.java:811) ~[?:?]
30.12 22:37:31 [Server] INFO at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.4.jar:git-Paper-346]
30.12 22:37:31 [Server] INFO at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
30.12 22:37:31 [Server] INFO at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
30.12 22:37:31 [Server] INFO at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1458) ~[paper-1.20.4.jar:git-Paper-346]
30.12 22:37:31 [Server] INFO at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:194) ~[paper-1.20.4.jar:git-Paper-346]
30.12 22:37:31 [Server] INFO at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
30.12 22:37:31 [Server] INFO at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1435) ~[paper-1.20.4.jar:git-Paper-346]
30.12 22:37:31 [Server] INFO at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1358) ~[paper-1.20.4.jar:git-Paper-346]
30.12 22:37:31 [Server] INFO at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
30.12 22:37:31 [Server] INFO at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1336) ~[paper-1.20.4.jar:git-Paper-346]
30.12 22:37:31 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1220) ~[paper-1.20.4.jar:git-Paper-346]
30.12 22:37:31 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[paper-1.20.4.jar:git-Paper-346]
30.12 22:37:31 [Server] INFO at java.lang.Thread.run(Thread.java:833) ~[?:?]
30.12 22:37:31 [Server] INFO Caused by: java.lang.NullPointerException: Cannot invoke "com.Zrips.CMI.Containers.CMIUser.getNickName()" because "<local24>" is null
30.12 22:37:31 [Server] INFO at com.Zrips.CMI.TabComplete.getByAction(TabComplete.java:1186) ~[CMI-9.6.9.3.jar:?]
30.12 22:37:31 [Server] INFO at com.Zrips.CMI.TabComplete.get(TabComplete.java:546) ~[CMI-9.6.9.3.jar:?]
30.12 22:37:31 [Server] INFO at com.Zrips.CMI.TabComplete.onTabComplete(TabComplete.java:100) ~[CMI-9.6.9.3.jar:?]
30.12 22:37:31 [Server] INFO at com.Zrips.CMI.TabComplete.get(TabComplete.java:366) ~[CMI-9.6.9.3.jar:?]
30.12 22:37:31 [Server] INFO at com.Zrips.CMI.Containers.CommandReg.onTabComplete(CommandReg.java:127) ~[CMI-9.6.9.3.jar:?]
30.12 22:37:31 [Server] INFO at com.Zrips.CMI.Containers.CommandReg$ReflectCommand.tabComplete(CommandReg.java:283) ~[CMI-9.6.9.3.jar:?]
30.12 22:37:31 [Server] INFO at org.bukkit.command.Command.tabComplete(Command.java:93) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
30.12 22:37:31 [Server] INFO at org.bukkit.command.SimpleCommandMap.tabComplete(SimpleCommandMap.java:240) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
30.12 22:37:31 [Server] INFO ... 20 more`
Thanks!

**Comment by Grantie** [comment]
I fixed this. It was due to another plugin. Thanks!
